# Generated by Django 5.2.6 on 2025-09-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0001_initial'),
    ]

    operations = [
    ]
